R"(
$188     $189     $18A     $18B     $18C     $18D     $18E     $18F     ;
:# # # # :# # # # :# # # # :# # # # :# # # # :# # # # :# # # # :# # # # |
:        :        :        :        :        :        :        :        |
:# # # # :# # # # :# # # # :# # # # :# # # # :# # # # :# # # # :# # # # |
:        :        :        :        :        :        :        :        |
:# # # # :# # # # :# # #   :        :        :# # # # :# # # # :# # # # |
:        :        :        :        :        :        :        :        |
:# # # # :# # # # :#       :        :        :    # # :# # # # :# # # # |
:        :        :       #:        :        :        :        :        |
$198     $199     $19A     $19B     $19C     $19D     $19E     $19F     ;
:# # # # :# # #   :      . :. .     :        :      # :# # # # :# # # # |
:        :        :        :        :        :        :        :        |
:# # # # :# #     :      . :. . . . :    . . :.       :# # # # :# # # # |
:        :        :       .: .      :        :        :        :        |
:# # # # :# #     :. . . . :c . . . :. . . . :.   .   :  # # # :# # # # |
:        :        : #     .:.  . .  :   # #  :        :        :        |
:# # # # :# #   .#:c . c c :c . c . :c . . . :. . . . :  # # # :# # # # |
:        :       .:.. . .  :   .    : . .    :        :        :        |
$1A8     $1A9     $1AA     $1AB     $1AC     $1AD     $1AE     $1AF     ;
:# # # # :#     c :c . c . :. . . . :. c c#. :. .     :    # # :# # # # |
:        :       .:   . c  :     .  :   . ...:        :        :        |
:# # # # :#     . :c c . c :. . . c :c c c c :c .   . :.   # # :# # # # |
:        :       .: . .   .:   .   .: .   .  : .      :        :        |
:# # # # :#   . . :c c . . :c . c#c :c c . . :. . .   :.     # :# # # # |
:        :     #  : .     .:     . c:c. .    : .      :        :        |
:# # # # :    . c :c . . c :c c c c :. c . . :. . . . :.     # :# # # # |
:        :       .: . .   c:cccccc .:.  .  ..:.c      :        :        |
$1B8     $1B9     $1BA     $1BB     $1BC     $1BD     $1BE     $1BF     ;
:# # # # :    . c :c c . cc:c.c.ccc :c . c.c.:ccc . . :.     # :# # # # |
:        :       .: c   ccc:cccccccc:cc . c c: ccc .  :        :        |
:# # # # :    . c :c c ccc :c c c.c.:c.c . . :c c.. . :.     # :# # # # |
:        :       .: .  ...c:cccc ccc:cc.  ccc:c. .    :        :        |
:# # # # :    . . :c ..c.c.:c.ccc.c.:c.c c.c.:c.c . c :.     # :# # # # |
:        :       .:   ccccc:cccccccc:cccccccc:cccc    :        :        |
:# # # # :#   . . :. ccc.c.:c.c.c.c.:c.c.c.c.:c.c.. . :    # # :# # # # |
:        :        :  cccccc:.ccccccc:cccccc.c:cccc    :        :        |
$1C8     $1C9     $1CA     $1CB     $1CC     $1CD     $1CE     $1CF     ;
:# # # # :#   .   :. c.c.. :#   c.c.:c.c.. # :  ccc . :    # # :# # # # |
:        :     .. :  cc.  c:c# # ccc:ccc.#c##:#c c.   :        :        |
:# # # # :#     c :. ccc c#:. c#c.c.:c.ccc . :ccc c . :    # # :# # # # |
:        :     c.c:  ccc. c:#c.ccccc:cc.cc##c:cc c..  :        :        |
:# # # # :#   ..c :. ccc.c.:c c.c.c.:c.c.c.c.:c.c.c . :    # # :# # # # |
:        :      .c:. cccccc:cccccccc:cc.ccccc:cccc..  :        :        |
:# # # # :#     c.:c ccc.c.:c.c.c.c.:c.c.c.c.:c.c.c   :  # # # :# # # # |
:        :       #:..cccccc:cccccccc:cccccccc:cccc    :        :        |
$1D8     $1D9     $1DA     $1DB     $1DC     $1DD     $1DE     $1DF     ;
:# # # # :#     .c:  ccc.c.:c.c.c.c.:c.c.c.c.:c.c.c # :  # # # :# # # # |
:        :      .c:  cccccc:cccccc c:cc .cccc:cccc    :        :        |
:# # # # :#     c :  ccc.c.:c.c.c.c.:c.c.c.c.:c.c.c # :    # # :# # # # |
:        :     cc :  #ccccc:.ccccccc:cccccccc:.ccc    :        :        |
:# # #   :    ..c :.  cc.c.:c.c.c.c.:c.c.c.c.:c.c.  # :    # # :# # # # |
:        :    .c  :    cccc:cccccccc:cccccccc:ccc#    :        :        |
:# #     :  # c   :. . ccc.:c.c.c.c.:c c.c.c.:c.c . . :    # # :# # # # |
:        :   c.   :     ccc:cccccc.c:cc.ccccc:cc      :        :        |
$1E8     $1E9     $1EA     $1EB     $1EC     $1ED     $1EE     $1EF     ;
:#       :c . . . :.   c cc:c.c.c.c.:c.c.c.c.:c . . . :      # :# # # # |
:     # c:cccc    :  # cc #:cccccccc:ccccccc.: cc     :        :        |
:     #c.:. ccc . :. c cc. :c.c.ccc :c c.c c :ccc   # :      # :# # # # |
:     ccc:.# cccc : ccc cc : . c.c .:   c . c:cc .    :        :        |
:    c.c :c.c c . :c cc.ccc:. . c c :. . . cc:ccc cc  :        :# # # # |
:   .cc.#:.ccc ccc:c  ccccc:cc   .  :   . .cc:cc #cc c:        :        |
:   cc.cc:c#cc. c.:c#cccccc:ccc . c :. c cccc:ccc ccc :c       :# # # # |
:   ccccc:cc c.  .:  cccccc:ccc# ...:  .ccccc:cc ccc#.:cccc    :        |
$1F8     $1F9     $1FA     $1FB     $1FC     $1FD     $1FE     $1FF     ;
:  c.c.c :c.c c c :c .ccccc:cccc  . :. cccccc:c ccccc :ccccc # :  # # # |
: cccccc#: cc  c #:cc ccccc:ccccc# c:cccccc  : ccccc c:cccc    :        |
:  c.c.c :c.c c # :ccc . cc:ccccccc :. ccc c#:ccccc cc:cccc. c :    # # |
:#cccccc :.. ..cc#:cccc   c:cccccccc: ccc ccc:cccc ccc:ccc#.ccc:        |
:c.c.ccc :.#c cccc:. ccccc :. cccccc:c . cccc:ccc cccc:cc. c.c.:c..   # |
:cccccc c:cc   ccc:c# ccccc: #  #ccc: #cccccc:c# cccc#:   ccccc:cccc    |
:c c . c :. c c cc:ccc cccc:cccc. c :ccccccc :. ccc # :c#..c.c.:c.c c   |
:cc #.cc : c .cc c:cccc   c:cccccccc:ccccc# c:cc   ccc:cc ccccc:cc....  |
)"
