R"(
$088     $089     $08A     $08B     $08C     $08D     $08E     $08F     ;
:# # # # :# # # # :# # # # :# # # # :# # # # :# # # # :# # # # :# # # # |
:        :        :        :        :        :        :        :        |
:# # # # :# # # # :# # # # :# # # # :# # # # :# # # # :# # # # :# # # # |
:        :        :        :        :        :        :        :        |
:# # # # :# # # # :# # #   :        :        :# # # # :# # # # :# # # # |
:        :        :        :        :        :        :        :        |
:# # # # :# # # # :#       :        :        :    # # :# # # # :# # # # |
:        :        :       .:        :        :        :        :        |
$098     $099     $09A     $09B     $09C     $09D     $09E     $09F     ;
:# # # # :# # #   :      . :. . .   :        :      # :# # # # :# # # # |
:        :        :       .:        :     .  :        :        :        |
:# # # # :# #     :  . . . :. . . . :.   . . :.       :# # # # :# # # # |
:        :        :       .:#.      :       .:        :        :        |
:# # # # :# #     :. . . .#:. . . . :. . . . :. . .   :  # # # :# # # # |
:        :       .:#. . . .:#. . . .:   . .#.:        :        :        |
:# # # # :# #   .#:. . . . :. . . . :. . . . :. . . . :  # # # :# # # # |
:        :      #.:#. . . .: . .   .: .#.    : .      :        :        |
$0A8     $0A9     $0AA     $0AB     $0AC     $0AD     $0AE     $0AF     ;
:# # # # :#     . :. . . . :. . . . :. c c . :. . .   :    # # :# # # # |
:        :     .#.:#. . .#.:     . .: . .#.#.: .      :        :        |
:# # # # :#     . :. . . .#:. . . . :. . . . :. . . . :.   # # :# # # # |
:        :     . .: . . . .: . . . .: . . . .: . .    :        :        |
:# # # # :#   . . :. . . . :c . . c :c . . . :. . . . :.     # :# # # # |
:        :     .#.: . . . .: .   .#c:.. . . .: . . .  :        :        |
:# # # # :    . . :. . . . :c c . . :.#. . . :. . . . :.     # :# # # # |
:        :     . .:#. . .#c:cc.c.c .:.. .....:.c.. . .:        :        |
$0B8     $0B9     $0BA     $0BB     $0BC     $0BD     $0BE     $0BF     ;
:# # # # :    . .#:c . .#..:c.c.c.c#:c . c.c.:c.c . . :.     # :# # # # |
:        :     .#.: c .#c.c:.c.ccc.c:.c ..c.c:.ccc .  :        :        |
:# # # # :    . . :.#. c.c#:. . c.c.:c.c . . :.#c.. . :.     # :# # # # |
:        :     . .:#. ....c:.c.c.ccc:.c.. c.c:.c.. .  :        :        |
:# # # # :    . . :. ..c.c.:c.c.c.c.:c.c c.c.:c.c . . :.     # :# # # # |
:        :     . .: .#ccc.c:.c.c.c.c:.c.c.c.c:.c.c    :        :        |
:# # # # :#   . . :. c.c.c.:c.c.c.c.:c.c.c.c.:c.c.. . :    # # :# # # # |
:        :        : .cc.c.c:.c.c.c.c:.c.c.c.c:.ccc#   :        :        |
$0C8     $0C9     $0CA     $0CB     $0CC     $0CD     $0CE     $0CF     ;
:# # # # :#   . . :. c.c.. :.  #c.c.:c.c.c . :  c.. . :    # # :# # # # |
:        :     ...: .cc.  .:#.#c.c.c:.c.c .#.: c c.   :        :        |
:# # # # :#   . c :. c.c c#:.#ccc.c.:c.ccc#.#:ccc.c . :    # # :# # # # |
:        :     c.c: .cc.c.c:#..ccc.c:.c.cc.#.:c..c..  :        :        |
:# # # # :#   ..c.:. c.c.c.:c.c.c.c.:c.c.c.c.:c.c.c c :    # # :# # # # |
:        :     ..c:..cc.c.c:.c.c.c.c:.c.c.c.c:.c.c..# :        :        |
:# # # # :#     c.:c#c.c.c.:c.c.c.c.:c.c.c.c.:c.c.c   :  # # # :# # # # |
:        :       .:...ccc.c:.c.c.c.c:.c.c.c.c:.c.c#   :        :        |
$0D8     $0D9     $0DA     $0DB     $0DC     $0DD     $0DE     $0DF     ;
:# # # # :#       :  . c.c.:c.c.c.c.:c.c.c.c.:c.c.c   :  # # # :# # # # |
:        :        :  #c#c.c:.c.c.c c:cc c.c.c:.c.c    :        :        |
:# # # # :        :. c ..c.:c.c.c.c.:c.c.c.c.:c.c.c   :    # # :# # # # |
:        :        : ....c.c:.c.c.c.c:.c.c.c.c:.c.c#   :        :        |
:# # #   :      . :..c c.c.:c.c.c.c.:c.c.c.c.:c.c.  . :    # # :# # # # |
:        :       .:.c .cc.c:.c.c.ccc:.ccc.c.c:.c..    :        :        |
:#       :      ..:c . c.c.:c.c.c.c.:c.c.c.c.:c.c . . :    # # :# # # # |
:        :     ccc:     c.c:.c.c.c.c:.c.c.c.c:cc      :        :        |
$0E8     $0E9     $0EA     $0EB     $0EC     $0ED     $0EE     $0EF     ;
:#       :. c.c . :.   c c.:c.c.c.c.:c.c.c.c.:c#. . . :      # :# # # # |
:       .:.c.c.c# :   .cc .:.ccc.c.c:.c.ccc..:#c      :        :        |
:      ..:c.c#c.c#:.#c cc. :c.c.c.c :.#c.c . :ccc . . :      # :# # # # |
:      .c:.c.c#ccc: ccc#cc.: .#c.c#.:#.#c .#c:cc#c#   :        :        |
:      c.:c#c.c#c.:c cccccc:. .#. . :. . . cc:cc.#c.. :        :# # # # |
:    #c.c:.c#ccc .:#.#ccccc:cc . . .: . . .cc:cc ccc#c:#       :        |
:    c.c.:c.c#c...:c.c cccc:ccc . c :.#. cccc:ccc ccc :c .     :  # # # |
:   c.c.c:.c.c#c#.:.c..cccc:ccc.#...: .#.cccc:cc#ccc c:cccc    :        |
$0F8     $0F9     $0FA     $0FB     $0FC     $0FD     $0FE     $0FF     ;
:  ..c.c.:. c.... :. c cccc:cccc. . :c#cccccc:c#ccccc :ccccc   :  # # # |
: ..c.c.c:# .c#.#c:#c ccccc:ccccc. c:cccccc .: ccccc#c:cccc    :        |
:  c.c.c.:..c#. . :ccc .#cc:ccccccc#:c#ccc#cc:ccccc#cc:cccc. c :    # # |
: c.c.c.c: . .#. .:.ccc..#c:cccccccc:.cc.#ccc:cccc#ccc:cccc.c.c:#       |
:..c.c.c :c . .#cc:. ccccc#:c#cccccc:c .#cccc:ccc#cccc:ccc c.c.:c..   # |
:cc .#. .:.c  #ccc:cc ccccc:..#.....:#ccccccc:..#ccccc:#.#c.c.c:.c.c    |
:c.c.c.c :  . c cc:ccc#cccc:cccc.#.#:ccccccc :.#ccc#. :c.c.c.c.:c.c c   |
:.c.c.c.c: c ccc c:cccc ##c:cccccccc:ccccc.#c:cc..#.cc:cc c.c.c:.c.c..  |
)"
