R"(
$088     $089     $08A     $08B     $08C     $08D     $08E     $08F     ;
:# # # # :# # # # :# # # # :# # # # :# # # # :# # # # :# # # # :# # # # |
:        :        :        :        :        :        :        :        |
:# # # # :# # # # :# # # # :# # # # :# # # # :# # # # :# # # # :# # # # |
:        :        :        :        :        :        :        :        |
:# # # # :# # # # :# # #   :        :        :# # # # :# # # # :# # # # |
:        :        :        :        :        :        :        :        |
:# # # # :# # # # :#       :        :        :    # # :# # # # :# # # # |
:        :        :       #:        :        :        :        :        |
$098     $099     $09A     $09B     $09C     $09D     $09E     $09F     ;
:# # # # :# # #   :      . :. .     :        :      # :# # # # :# # # # |
:        :        :        :        :        :        :        :        |
:# # # # :# #     :      . :. . . . :    . . :.       :# # # # :# # # # |
:        :        :       .: .      :        :        :        :        |
:# # # # :# #     :. . . . :c . . . :. . . . :.   .   :  # # # :# # # # |
:        :        : #     .:.  . .  :   # #  :        :        :        |
:# # # # :# #   .#:c . c c :c . c . :c . . . :. . . . :  # # # :# # # # |
:        :       .:.. . .  :   .    : . .    :        :        :        |
$0A8     $0A9     $0AA     $0AB     $0AC     $0AD     $0AE     $0AF     ;
:# # # # :#     c :c . c . :. . . . :. c c#. :. .     :    # # :# # # # |
:        :       .:   . c  :     .  :   . ...:        :        :        |
:# # # # :#     . :c c . c :. . . c :c c c c :c .   . :.   # # :# # # # |
:        :       .: . .   .:   .   .: .   .  : .      :        :        |
:# # # # :#   . . :c c . . :c . c#c :c c . . :. . .   :.     # :# # # # |
:        :     #  : .     .:     . c:c. .    : .      :        :        |
:# # # # :    . c :c . . c :c c c c :. c . . :. . . . :.     # :# # # # |
:        :       .: . .   c:cccccc .:.  .  ..:.c      :        :        |
$0B8     $0B9     $0BA     $0BB     $0BC     $0BD     $0BE     $0BF     ;
:# # # # :    . c :c c . cc:c.c.ccc :c . c.c.:ccc . . :.     # :# # # # |
:        :       .: c   ccc:cccccccc:cc . c c: ccc .  :        :        |
:# # # # :    . c :c c ccc :c c c.c.:c.c . . :c c.. . :.     # :# # # # |
:        :       .: .  ...c:cccc ccc:cc.  ccc:c. .    :        :        |
:# # # # :    . . :c ..c.c.:c.ccc.c.:c.c c.c.:c.c . c :.     # :# # # # |
:        :       .:   ccccc:cccccccc:cccccccc:cccc    :        :        |
:# # # # :#   . . :. ccc.c.:c.c.c.c.:c.c.c.c.:c.c.. . :    # # :# # # # |
:        :        :  cccccc:.ccccccc:cccccc.c:cccc    :        :        |
$0C8     $0C9     $0CA     $0CB     $0CC     $0CD     $0CE     $0CF     ;
:# # # # :#   .   :. c.c.. :#   c.c.:c.c.. # :  ccc . :    # # :# # # # |
:        :     .. :  cc.  c:c# # ccc:ccc.#c##:#c c.   :        :        |
:# # # # :#   . c :. ccc c#:. c#c.c.:c.ccc . :ccc c . :    # # :# # # # |
:        :     c.c:  ccc. c:#c.ccccc:cc.cc##c:cc c..  :        :        |
:# # # # :#   ..c :. ccc.c.:c c.c.c.:c.c.c.c.:c.c.c . :    # # :# # # # |
:        :      .c:. cccccc:cccccccc:cc.ccccc:cccc..  :        :        |
:# # # # :#     c.:c ccc.c.:c.c.c.c.:c.c.c.c.:c.c.c   :  # # # :# # # # |
:        :        :c.cccccc:cccccccc:cccccccc:cccc    :        :        |
$0D8     $0D9     $0DA     $0DB     $0DC     $0DD     $0DE     $0DF     ;
:# # # # :#       :  c c.c.:c.c.c.c.:c.c.c.c.:c.c.c # :  # # # :# # # # |
:        :        :   c ccc:cccccc c:cc .cccc:cccc    :        :        |
:# # # # :#       :. c ..c.:c.c.c.c.:c.c.c.c.:c.c.c # :    # # :# # # # |
:        :        : #c cccc:.ccccccc:cccccccc:.ccc    :        :        |
:# # #   :      . :.cc c.c.:c.c.c.c.:c.c.c.c.:c.c.  # :    # # :# # # # |
:        :       #:cc  cccc:cccccccc:cccccccc:ccc#    :        :        |
:# #     :      ..:c   ccc.:c.c.c.c.:c c.c.c.:c.c . . :    # # :# # # # |
:        :     ccc:     ccc:cccccc.c:cc.ccccc:cc      :        :        |
$0E8     $0E9     $0EA     $0EB     $0EC     $0ED     $0EE     $0EF     ;
:#       :. c.c c :    c cc:c.c.c.c.:c.c.c.c.:c . . . :      # :# # # # |
:       #:cc.ccc  :  # cc #:cccccccc:ccccccc.: cc     :        :        |
:      ..:c.c c.c :  c cc. :c.c.ccc :c c.c c :ccc   # :      # :# # # # |
:      cc:.ccc#ccc:.ccc cc : . c.c .:   c . c:cc .    :        :        |
:      c.:c ccc c :c cc.ccc:. . c c :. . . cc:ccc cc  :        :# # # # |
:     c.c:cc#ccc #:.. ccccc:cc   .  :   . .cc:cc #cc c:        :        |
:    c.c.:ccc c..c:ccc cccc:ccc . c :. c cccc:ccc ccc :c       :# # # # |
:   ccccc:.ccc c .:.c. cccc:ccc# ...:  .ccccc:cc ccc#.:cccc    :        |
$0F8     $0F9     $0FA     $0FB     $0FC     $0FD     $0FE     $0FF     ;
:  ..c.cc:c ..... :. . cccc:cccc  . :. cccccc:c ccccc :ccccc # :  # # # |
: #cccccc:  .c  .c: # ccccc:ccccc# c:cccccc  : ccccc c:cccc    :        |
:  c.c.c.:..c .#c :ccc . cc:ccccccc :. ccc c#:ccccc cc:cccc. c :    # # |
: ccccccc:   # .##:cccc   c:cccccccc: ccc ccc:cccc ccc:ccc#.ccc:        |
:..c.c.c :c.c . cc:. ccccc :. cccccc:c . cccc:ccc cccc:cc. c.c.:c..   # |
:cc     .:..   ccc:c# ccccc: #  #ccc: #cccccc:c# cccc#:   ccccc:cccc    |
:c.c c.c :  c c cc:ccc cccc:cccc. c :ccccccc :. ccc # :c#..c.c.:c.c c   |
:cccccccc: c .cc c:cccc   c:cccccccc:ccccc# c:cc   ccc:cc ccccc:cc....  |
)"
