R"(
$188     $189     $18A     $18B     $18C     $18D     $18E     $18F     ;
:# # # # :# # # # :# # # # :# # # # :# # # # :# # # # :# # # # :# # # # |
:        :        :        :        :        :        :        :        |
:# # # # :# # # # :# # # # :# # # # :# # # # :# # # # :# # # # :# # # # |
:        :        :        :        :        :        :        :        |
:# # # # :# # # # :# # #   :        :        :# # # # :# # # # :# # # # |
:        :        :        :        :        :        :        :        |
:# # # # :# # # # :#       :        :        :    # # :# # # # :# # # # |
:        :        :       .:        :        :        :        :        |
$198     $199     $19A     $19B     $19C     $19D     $19E     $19F     ;
:# # # # :# # #   :      . :. . .   :        :      # :# # # # :# # # # |
:        :        :       .:        :     .  :        :        :        |
:# # # # :# #     :  . . . :. . . . :.   . . :.       :# # # # :# # # # |
:        :        :       .:#.      :       .:        :        :        |
:# # # # :# #     :. . . .#:. . . . :. . . . :. . .   :  # # # :# # # # |
:        :       .:#. . . .:#. . . .:   . .#.:        :        :        |
:# # # # :# #   .#:. . . . :. . . . :. . . . :. . . . :  # # # :# # # # |
:        :      #.:#. . . .: . .   .: .#.    : .      :        :        |
$1A8     $1A9     $1AA     $1AB     $1AC     $1AD     $1AE     $1AF     ;
:# # # # :#     . :. . . . :. . . . :. c c . :. . .   :    # # :# # # # |
:        :     .#.:#. . .#.:     . .: . .#.#.: .      :        :        |
:# # # # :#     . :. . . .#:. . . . :. . . . :. . . . :.   # # :# # # # |
:        :     . .: . . . .: . . . .: . . . .: . .    :        :        |
:# # # # :#   . . :. . . . :c . . c :c . . . :. . . . :.     # :# # # # |
:        :     .#.: . . . .: .   .#c:.. . . .: . . .  :        :        |
:# # # # :    . . :. . . . :c c . . :.#. . . :. . . . :.     # :# # # # |
:        :     . .:#. . .#c:cc.c.c .:.. .....:.c.. . .:        :        |
$1B8     $1B9     $1BA     $1BB     $1BC     $1BD     $1BE     $1BF     ;
:# # # # :    . .#:c . .#..:c.c.c.c#:c . c.c.:c.c . . :.     # :# # # # |
:        :     .#.: c .#c.c:.c.ccc.c:.c ..c.c:.ccc .  :        :        |
:# # # # :    . . :.#. c.c#:. . c.c.:c.c . . :.#c.. . :.     # :# # # # |
:        :     . .:#. ....c:.c.c.ccc:.c.. c.c:.c.. .  :        :        |
:# # # # :    . . :. ..c.c.:c.c.c.c.:c.c c.c.:c.c . . :.     # :# # # # |
:        :     . .: .#ccc.c:.c.c.c.c:.c.c.c.c:.c.c    :        :        |
:# # # # :#   . . :. c.c.c.:c.c.c.c.:c.c.c.c.:c.c.. . :    # # :# # # # |
:        :        : .cc.c.c:.c.c.c.c:.c.c.c.c:.ccc#   :        :        |
$1C8     $1C9     $1CA     $1CB     $1CC     $1CD     $1CE     $1CF     ;
:# # # # :#   . . :. c.c.. :.  #c.c.:c.c.c . :  c.. . :    # # :# # # # |
:        :     ...: .cc.  .:#.#c.c.c:.c.c .#.: c c.   :        :        |
:# # # # :#   . c :. c.c c#:.#ccc.c.:c.ccc#.#:ccc.c . :    # # :# # # # |
:        :     c.c: .cc.c.c:#..ccc.c:.c.cc.#.:c..c..  :        :        |
:# # # # :#   ..c.:. c.c.c.:c.c.c.c.:c.c.c.c.:c.c.c c :    # # :# # # # |
:        :     ..c:..cc.c.c:.c.c.c.c:.c.c.c.c:.c.c..# :        :        |
:# # # # :#     ..:c#c.c.c.:c.c.c.c.:c.c.c.c.:c.c.c   :  # # # :# # # # |
:        :       .:..cccc.c:.c.c.c.c:.c.c.c.c:.c.c#   :        :        |
$1D8     $1D9     $1DA     $1DB     $1DC     $1DD     $1DE     $1DF     ;
:# # # # :#     ..:  c.c.c.:c.c.c.c.:c.c.c.c.:c.c.c   :  # # # :# # # # |
:        :       .: .cccc.c:.c.c.c c:cc c.c.c:.c.c    :        :        |
:# # # # :      c :. c.c.c.:c.c.c.c.:c.c.c.c.:c.c.c   :    # # :# # # # |
:        :     c..:  #ccc.c:.c.c.c.c:.c.c.c.c:.c.c#   :        :        |
:# # #   :    ..c :. ..c.c.:c.c.c.c.:c.c.c.c.:c.c.  . :    # # :# # # # |
:        :    .c  :   .cc.c:.c.c.ccc:.ccc.c.c:.c..    :        :        |
:#       :  . c . :. . c.c.:c.c.c.c.:c.c.c.c.:c.c . . :    # # :# # # # |
:        :   c    :     c.c:.c.c.c.c:.c.c.c.c:cc      :        :        |
$1E8     $1E9     $1EA     $1EB     $1EC     $1ED     $1EE     $1EF     ;
:#       :. .#. . :.   c c.:c.c.c.c.:c.c.c.c.:c#. . . :      # :# # # # |
:     # c:cccc#   :   .cc .:.ccc.c.c:.c.ccc..:#c      :        :        |
:    .#c.:c.ccc . :. c cc. :c.c.c.c :.#c.c . :ccc . . :      # :# # # # |
:     c.c:...ccc. :#ccc#cc.: .#c.c#.:#.#c .#c:cc#c#   :        :        |
:    c.c.:c.c#c#. :. cccccc:. .#. . :. . . cc:cc.#c.. :        :# # # # |
:   .cc..:.ccc ccc:c. ccccc:cc . . .: . . .cc:cc ccc#c:#       :        |
:  ..c.c.:c c.c.c.:c cccccc:ccc . c :.#. cccc:ccc ccc :c .     :  # # # |
:  #ccccc:cc#c.. .:#..ccccc:ccc.#...: .#.cccc:cc#ccc c:cccc    :        |
$1F8     $1F9     $1FA     $1FB     $1FC     $1FD     $1FE     $1FF     ;
:  c.c.c :c.c c c#:c#.ccccc:cccc. . :c#cccccc:c#ccccc :ccccc   :  # # # |
: cccccc.:#c.. c .:cc ccccc:ccccc. c:cccccc .: ccccc#c:cccc    :        |
: #c.c.c :..c .#. :ccc .#cc:ccccccc#:c#ccc#cc:ccccc#cc:cccc. c :    # # |
:#ccccc..:.. .#cc.:.ccc..#c:cccccccc:.cc.#ccc:cccc#ccc:cccc.c.c:#       |
:c.c.c.c :. . cccc:. ccccc#:c#cccccc:c .#cccc:ccc#cccc:ccc c.c.:c..   # |
:cccccc#c:.c# #ccc:cc ccccc:..#.....:#ccccccc:..#ccccc:#.#c.c.c:.c.c    |
:c c . c :. . c cc:ccc#cccc:cccc.#.#:ccccccc :.#ccc#. :c.c.c.c.:c.c c   |
:cc#. c..: . ccc c:cccc ##c:cccccccc:ccccc.#c:cc..#.cc:cc c.c.c:.c.c..  |
)"
