R"(
$108     $109     $10A     $10B     $10C     $10D     $10E     $10F     ;
:cccccccc:cccccccc:cccccccc:cccccccc:cccccccc:cccccccc:c.cccccc:c...c.cc|
:cccccccc:cccccccc:cccccccc:cccccccc:cccccccc:cccccccc:cc.c.c.c:cc....cc|
:cccccccc:cccccccc:ccccccc#:c#.#c.c.:c.cccccc:c.cccccc:c.c.c.c.:c.....c.|
:cccccccc:cccccccc:ccccc.#c:. .ccccc:..cccccc:cccccccc:cccccccc:........|
:cccccccc:cccccccc:cccc.#c#:. .cc#. :.cccc.c.:c#cccccc:cccccccc:c.c.c...|
:cccccccc:cccccccc:cccc .#.:  ..    :........:.ccccccc:cccccccc:cccccc..|
:cccccccc:cccccccc:c#c#. .#:. . . . :. . .#c.:cccccccc:cccccccc:ccccccc.|
:cccccccc:cccccccc:........:........:#. .  ..:.ccccccc:cccccccc:cccccccc|
$118     $119     $11A     $11B     $11C     $11D     $11E     $11F     ;
:cccccccc:cccccccc:.#c.c.c.:c.c.c..#:.#. . . :. .#cccc:cccccccc:ccc.c.c.|
:cccccccc:cccccccc:.c.ccc..:...cc...:..      :   .cccc:cccccccc:cccccccc|
:cccccccc:ccccccc#:c.c.c..#:.#.#.#. :. . . . :. . cccc:cccccccc:ccc.c.cc|
:cccccccc:cccccc..:.ccccccc:cc.c....:..      :     ccc:cccccccc:cccccc..|
:cccccccc:ccccc#.#:c.c.c.c.:c.c.c.c#:. . . . :. . . cc:ccccccc.:ccc.ccc.|
:cccccccc:cccc.ccc:cccccc.c:.ccc.. .:#.   .  :       c:cccccccc:.ccccccc|
:cccccccc:ccc#..c.:c.c.c.c.:c#c.. . :. . . . :. . . . :ccccc.c.:c.c.c.cc|
:cccccccc:cc#. ccc:cccccccc:......  : .......:        :.ccccccc:cccc...c|
$128     $129     $12A     $12B     $12C     $12D     $12E     $12F     ;
:cccccccc:c#.#..c.:c.c.c.c.:.#. .#. :. .#.#.#:. . . . :..cccccc:ccccccc.|
:cccccccc:ccc..ccc:cccc.c..: .#. . .: . ...  : .#.    : .cccccc:cccccccc|
:cccccccc:ccc#c.c.:c.c.ccc.:c#c#. .#:. . . .#:. . . . :.#cccccc:ccccc.cc|
:cccccccc:cc..cccc:cc.ccccc:cc.c....:.c ....c:.  .    : .cccccc:cccccc.c|
:cccccccc:cc. c..#:....cccc:ccc.c.c.:ccc#ccc.:c#. . . :. cccccc:c.ccc.cc|
:cccccccc:cc#.....: ..ccccc:cccccccc:.ccc.ccc:cc.c    : ..ccccc:cc.ccc.c|
:cccccccc:ccc . . :. ..cccc:cccccccc:c.cccccc:ccc.. . :. c.c.c.:c...c.c.|
:cccccccc:cc.     :   ccccc:cccccccc:cccccccc:cc.c....: ..ccccc:cc...c.c|
$138     $139     $13A     $13B     $13C     $13D     $13E     $13F     ;
:cccccccc:ccc . . :. .ccccc:cccccccc:cccccccc:ccc.c#. :. cccccc:ccc.c.c.|
:cc.ccccc:cc#     : ..ccccc:cccccccc:cccccccc:ccccc. .: .cccccc:ccccc...|
:c.c.cccc:ccc . . :. cccccc:cccccccc:cccccccc:ccccc#. :.#cccccc:ccccc.c.|
:...ccccc:cc.. . .:#.cccccc:cccccccc:cccccccc:ccccc. .: .cccccc:cccccccc|
:c.cccccc:ccc .#. :.#ccc.c.:c.cccccc:ccccccc.:c.ccc#. :.#cccccc:ccccccc.|
:...ccccc:cc.. .#.:..cc....: ....ccc:cccc....: ..cc. .:.ccccccc:cccccccc|
:c.cccccc:ccc#. . :.#ccc.c.:c.c#c.cc:ccc...c.:c.c.c#. :.#cccccc:ccc.cccc|
:...ccccc:cccc   .: .cccccc:cccccccc:cccccccc:ccccc.  :#ccccccc:cccccccc|
$148     $149     $14A     $14B     $14C     $14D     $14E     $14F     ;
:c.cccccc:cccc. c#:.#ccccc#:. .#cccc:ccc..#. :.#ccc#. :.#cccccc:cccccccc|
:c.cccccc:cc..cc#c:#.cccc#c:..#ccccc:ccccc.#c:c..ccc. :#.cccccc:cccccccc|
:c.ccccc.:cc.#c..c:. cccccc:c#cccccc:ccccc#.c:ccccc.c :.#cccccc:cccccccc|
:.ccccc..:cc#..c.c:c.cccccc:cccccccc:cccccccc:cccccc..:#.cccccc:cccccccc|
:ccccc.c.:cc.#c.cc:c#cccccc:cccccccc:cccccccc:ccccccc#:.#cccccc:ccc.ccc.|
:cccccc..:ccc..ccc:cccccccc:cccccccc:cccccccc:cccccccc:.ccccccc:cccc.ccc|
:ccccc.c.:ccc#cccc:cccccccc:cccccccc:cccccccc:ccccccc.:.ccccccc:ccc.c.c.|
:cccccc..:cccc#ccc:cccccccc:cccccccc:cccccccc:cccccc..:.ccccccc:cccccccc|
$158     $159     $15A     $15B     $15C     $15D     $15E     $15F     ;
:ccccc.c.:ccccc#cc:cccccccc:cccccccc:ccc.cccc:ccccc..#:ccc.cccc:cccccccc|
:ccccc..c:cccccc#.:cccccccc:cccccccc:cccccccc:cccccc.c:cccccccc:cccccccc|
:ccccc.c#:ccccccc#:cccccccc:ccccccc.:c..#cccc:ccccc...:ccccc.cc:ccccc.cc|
:cccc...c:.....c.c:#ccccccc:cccccc.c:cc.ccccc:ccccc..c:cccccc.c:cccccccc|
:ccc#c..#:c#.#. . :.#cccccc:c.cccccc:ccccc.cc:ccccc#.#:c.ccccc.:ccccc.cc|
:.c....#.:....#.#.: #cccccc:.ccccccc:ccccc.cc:ccccc.  : ccccc..:.ccccccc|
:c#. .#.#:c.. . . :. cccccc:c#.#.#.#:.#.#..cc:ccccc . :. ..c.c.:c.cccccc|
:..#.#...:....    :  #ccccc:cccc.c.c:.c.ccccc:cccc....:.. ccccc:cc.ccccc|
$168     $169     $16A     $16B     $16C     $16D     $16E     $16F     ;
:c#.#.#.#:c.. . . :.  .cccc:cccccccc:cccccccc:ccc..#c.:c#.#cccc:ccc.c.c.|
:.c###.#.:.c..   .:   .cccc:cccccccc:cccccccc:ccc.  .c:....cccc:cccccc..|
:c#. .#. :..c . . :. .#.#.#:.#.#cccc:cccccccc:c.. . ..:c#c.c.cc:c.c.c.c.|
:.. ##.##: ... #  : ccccccc:ccc.cccc:cccccccc:c..c#  .:cc.ccccc:.c.c...c|
:. . ... :. . . . :.ccccccc:ccc#cccc:ccccccc.:. .#c#. :c...c.c.:c.c.c.c.|
:.. ##c..: #   .cc:#ccccccc:ccc..ccc:cccc...c:.. ..c..:.c.c.c.c:.c.c....|
:. . ..c :  . .#. :.ccccccc:ccc#. . :. . .#c.:c#.#.#c#:.ccccccc:c.c.c...|
:.. # ...:#ccc.c..:#ccccccc:ccc..c.c:.c.c.c.c:cc # ...:.ccccccc:cccccc..|
$178     $179     $17A     $17B     $17C     $17D     $17E     $17F     ;
:. . . . :c.c#. .#:.ccccccc:ccc#c.c.:c.c.c.c.:c..#. .#:c#cccccc:ccccc.c.|
:.. # # c:c. # .#.:#ccccccc:ccc..c.c:.c.c.c.c:cc#c.# #:#c.ccccc:ccccccc.|
:. . . ..:c.c.c#.#:.ccccccc:ccc#c.c.:c.c.c.c.:c#cccc.#:. .#c#cc:ccccccc.|
:#. #  .c:c.#..c#.:#ccccccc:ccc..c.c:.c.c.ccc:c.cccccc:cc#. ..c:.ccccccc|
:.#.#. ..:c.c#.#.#:.ccccccc:ccc#c.c.:c.c.c.cc:c#cccccc:cccccc.#:.#c#c#c.|
:.cccc..c:cc.cc. .:#ccccccc:ccc..c.c:.c.ccccc:..cccccc:cccccccc:cc.c....|
:ccccc#..:c#.#...#:.ccccccc:ccc#c.c.:c.c.cccc:.ccccccc:cccccccc:cccccccc|
:ccccc..c:cc..#.. : .#.#.#.:#.#.cccc:.ccccccc:#ccccccc:cccccccc:cccccccc|
)"
