R"(
$108     $109     $10A     $10B     $10C     $10D     $10E     $10F     ;
:c#c#c#c#:c#c#c#c#:c#c#c#c#:c#c c.c :c#c#c#c :c c.c.c.:c#c.c.c.:c . . c.|
:.c.c.c.c:.c.c.c.c:.c.c.c.c:.c...c.c:.c.c.c.c:...c.c.c:........:.c . ..c|
:c#c#c c :c c#c#c#:c#c#c#c :c . c c :c#c.c.c.:c c.c.c.:c .#.#c :.#c . . |
:cccccccc:cccccc.c:.c.c..#c:   c.c..:.....c.c:.c.c.c.c:.c.c.c..:.. . . .|
:cccccccc:c c c c :c c#. c :. . c . :. c c c :c ..c.c.:c.c.c.c :c .#. . |
:cccccccc:cccccccc:cc.c    :   #    : . . .#.:#..c.c.c:.c.c.c.c:.c.... .|
:ccccccc :c c c c :c c . . :. . . . :. . . .#:c c c c.:c.c.c.c.:c.c.c.c#|
:.ccccccc:cccccccc: .#  ...: . . .  :       .: ..c c.c:.c.c.c.c:.c......|
$118     $119     $11A     $11B     $11C     $11D     $11E     $11F     ;
:c#c#c#c#:c#c#c#c#:. . c c :c c c#c :. . . . :. . c c#:c.c.c.c.:c c c c |
:.c.c.c.c:.c.c.c.c: . .....: .#. .  :        :   #.c.c:.c.c.c.c:........|
:c#c#c#c#:c#c#c#c :. c c#. :c c c . :. . . . :. . c#c.:c.c.c.c.:c.c c#c.|
:.c.c.c.c:.c.c.c#.:#.......:.. ...  :        :     ..c:.c.c.c..:.c......|
:c#c#c#c#:c#c#. . :c c c c :c c .#. :. . . . :. . . ..:c.c.c.c :c.c c.c |
:.c.c.c.c:.c..#...:.....c .: ...    :        :       .:.c.c....:.......c|
:c#c#c#c#:c#c c c :c c c c :. . c . :. . . . :. . . . :..c.c c :.#.#. c.|
:.c.c.c.c:.c#  ...:........: .   .  :        :        : c.c.c.c:.......c|
$128     $129     $12A     $12B     $12C     $12D     $12E     $12F     ;
:c#c#c#c#:c . .#c :c c c c :c . . . :. . . . :. . . . :.#c.c.c.:c.c.c .#|
:.c.c.c.c:#c.. ...:....#.  :        :        :        : ..c.c.c:.c.c.c..|
:c c c#c#:c#c . c :c . c.c :. . . . :c . . . :. . . . :. c.c.c.:c.c c c.|
:cccccc.c:.c . ...:.. c.c.c:..#. . .:#. . .#.:        :  .c.c.c:...c...c|
:c c c c#:c c c#c :c c c.c.:c.c c#c :. c ..c :c . . . :. c.c.c.:c#c.c#..|
:cccccc.c:.c#  .  :   ..c.c:.c.c...c:.......c:..#.    :  ...c.c:........|
:c c c#c#:c#. . . :. . c.c.:c.c.c.c.:c c.c c.:c . c . :. c . c :.#c#c . |
:.c.c.c.c:.c      :   ..c.c:.c.c.c.c:.c.c.c.c:.c..#   :  ......:........|
$138     $139     $13A     $13B     $13C     $13D     $13E     $13F     ;
:c#c#c#c#:c#c . . :. . c.c.:c.c.c.c.:c.c.c.c.:c.c c . :. c.c.c.:c.c#c .#|
:.c.c.c.c:.c      :  #c.c.c:.c.c.c.c:.c.c.c.c:.c.c..  :  .c.c.c:.c.c.. .|
:c#c c#c#:c#c . . :. c.c.c.:c.c.c.c.:c.c.c.c.:c.c.c . :. c.c.c.:c.c.c . |
:.....c.c:.c      :  .c.c.c:.c.c.c.c:.c.c.c.c:.c.c..  : ..c.c.c:.c.c.c..|
:c c c#c#:c#c . . :. c.c c :. c.c.c.:c.c.c c :. c.c . :. c c.c.:c.c.c.c |
:...c.c.c:.c      : ..c .  : . ..c.c:.c..#.  : . ...  : c...c.c:.c.c.c..|
:c c c#c#:c#c . . :. c.c c :c . . c.:c.c#. c :c c c . :. c#c.c.:c.c c.c.|
:...c.c.c:.c.c    :  .c.c.c:.c...c.c:.c.c.c.c:.c.c..  :#. c.c.c:.c...c.c|
$148     $149     $14A     $14B     $14C     $14D     $14E     $14F     ;
:c#.#c#c#:c#c c . :. c.c . :. . ..c.:c.c#. . :. c.c . :. c c c.:c.c.c.c.|
:...c.c.c:.c ...#c:  .c..#c: # c.c.c:.c.c.. #:...c..# : ..c.c.c:.c.c.c.c|
:.#c#c .#:c#. c#. :. c.c c.:c c c.c.:c.c c c :c c.c c :. c c c.:c.c.c.c.|
:...c....:.c#... .:  .c.c.c:.c.c.c.c:.c.c.c.c:.c.c... : ..c.c.c:.c......|
:. c#c#c :.#. c . :c c.c.c.:c.c.c.c.:c.c.c.c.:c.c.c c :c c.c.c.:c c#c c |
:.c.c....:.c#....c:c..c.c.c:.c.c.c.c:.c.c.c.c:.c.c.c..: ..c.c.c:.c.....c|
:c#c#c#.#:c#c . c :c c.c.c.:c.c.c.c.:c.c.c.c.:c.c.c c :c c.c.c.:c.c c .#|
:.c.c....:.c.c c.c:.c.c.c.c:.c.c.c.c:.c.c.c.c:.c.c.. .:.c.c.c.c:.c.c.c..|
$158     $159     $15A     $15B     $15C     $15D     $15E     $15F     ;
:c#c#c#c#:c#c#c c :c#c.c.c.:c.c.c.c.:c.c c.c.:c.c.c#. :c.c c.c.:c.c.c.c.|
:.c.c....: c c#c##:.c.c.c.c:.c.c.c.c:.c...c.c:.c.c.. .:.c.c.c.c:.c.c.c.c|
:c#c c . :c c c c :.#c.c.c.:c.c.c . :c c c.c.:c.c.c c :c.c.c#c.:c.c.c c.|
:.c.c .#.:#.   . .:#c.c.c.c:.c.c.c.c:..#..c.c:.c.c.. .:.c.c...c:.c.c...c|
:c c . . :c . . . :. c.c.c.:c c.c.c.:c.c.c c :c c.c . :. c.c.c :c.c.c c.|
: . . .#.:..   #  :  .c.c.c: ..c.c.c:.c.c...c:.c.c.   : .......:.c.c...c|
:. . c . :. c . . :. c c.c.:c . . . :. . . c.:c.c.c . :. .#c .#:. c.c.c.|
:.. . . .:.. .    :  #c.c.c:.c..#.#.:#.#. c.c:.c.c .#.:   ..c.c:.......c|
$168     $169     $16A     $16B     $16C     $16D     $16E     $16F     ;
:c c c c :c c . . :.   c.c.:c.c.c.c.:c.c.c.c.:c.c . c#:.#. c.c.:c.c c . |
:..   .  :#.      :   ..c.c:.c.c.c.c:.c.c.c.c:.c.   #c:#....c.c:.c......|
:. . . . :.#c . . :. . . . :. . c.c.:c.c.c.c.:c c . . :c#. c c :c c .#c#|
:     .  : .#     : c#c#c#c:.c #.c.c:.c.c.c.c:..#.#   :..#c.c..:.... ...|
:c . . . :. . . . :.#c cccc:ccc c.c.:c.c.c c :. . c . :.#. c c#:.#.#. .#|
:     .. :     . c: ccccccc:ccc.#. .: . .#.#.:.  .#.. : .......:...... .|
:. c .#. :  . . c :.#c cccc:ccc . . :. . c . :c . . c :c c c.c :c c c#. |
:.    .# : ..c....:#ccccccc:ccc# ...:.... ...:..   . .:.c.c.c.c:...... .|
$178     $179     $17A     $17B     $17C     $17D     $17E     $17F     ;
:. . c . :c . . . :.#c cccc:ccc . c :c c c c :c . . . :c c c.c.:c.c c . |
:.      .:..   .##:#ccccccc:ccc.#...:........:..#c##  :#c ..c.c:.c.c.c..|
:c c . c :c . . . :.#c cccc:ccc . c :c c c c :c c c . :. . c c.:c.c.c.c#|
:      #c:.. ...  :#ccccccc:ccc.#...:.......c:.. ccccc: c#   #.:.c.c.c..|
:. . . . :c c c . :.#c cccc:ccc . c :c c c c.:c cccccc:ccc#c . :. . . c |
: . cc. .:.. c.. #:#ccccccc:ccc.....:.....c.c:..cccccc:cccccccc:cc c . #|
:ccccc c :c . . . :. c cccc:ccc c c :c c c.c :. cccccc:cccccccc:ccccc#c |
:ccccc. .:.c .  # : ##. # #: # ..c..:...c.c.c:#ccccccc:cccccccc:cccccccc|
)"
