R"(
$180     $181     $182     $183     $184     $185     $186     $187     ;
:ccc c cc:cccccccc:cccccccc:cccccccc:cccccccc:ccccc c :cccccccc:cccccccc|
:ccc c cc:cccccccc:cccccccc:cccccccc:cccccccc:cccc c c:cccccccc:cccccccc|
:ccc c cc:cccccccc:ccccccc :c c cccc:c cccccc:ccccc c :cccccccc:cccccccc|
:ccc c cc:cccccccc:cccccc c:  .ccccc:cccccccc:cccc c c:cccccccc:cccccccc|
:ccc c cc:cccccccc:ccccc c :. ccc c :cccccccc:c c c c :cccccccc:cccccccc|
:ccc c cc:cccccccc:cccc ...:   .    : . . c c: ccc c c:cccccccc:cccccccc|
:ccc c cc:cccccccc:c c . . :c . . . :. . . c :ccccc c :ccc c c :cccccccc|
:ccc c cc:cccccccc: . .....:........:.. .  ..: ccc c c:cccccc c:cccccccc|
$190     $191     $192     $193     $194     $195     $196     $197     ;
:ccc c cc:cccccccc:c c c c :c c c c :c c . . :. . c c :ccccc c :c c c c |
:ccc   cc:cccccccc:...c.c .:...c....:..      :   . c c:cccc c c:cccc c c|
:ccc c cc:ccccccc :c c c c :c c c c :c . . . :. . c c :c c c c :c c c c |
:ccc   cc:cccccc .:.c.c.c.c:.c......:..      :        : ccccc c: ccccc  |
:ccc c cc:c c c c :c c c c :c.c c c :c . . . :. . . c :c c ccc :c c c c |
:ccc   cc:   . c.c:.c.c.c c:.c.c.. .:..   .  :       .:  #  ccc: c ccccc|
:ccc c c :c c c c :c c c c.:c c c . :. c . . :. . . . :c c c c :c c c c |
:ccc  ccc:  .  ..c:.c.c.c.c: .....  : .......:        :.    ccc:cccc ccc|
$1A0     $1A1     $1A2     $1A3     $1A4     $1A5     $1A6     $1A7     ;
:ccc c c :c c c c :c c c c :c c c c :. . c c :. . . . :. c c cc:c c c c |
:ccc  c  : . ..c.c:.c.. ...:  .. . .: .   .  :   .    : .     c: ccccc c|
:ccc c c :c c c c :c.c c.c.:c c . . :c . . . :. . . . :. c c c :c c c c |
:ccc     : c ..c.c:.c ccc.c:.c.c....: . ... c:.  .    :   c    :   ccc c|
:ccc c c :c . c c :c c c.c.:c.c.c c.:c.c c.c.:c . . . :. c c c :c c c c |
:ccc     :   .....: ..ccc.c:.c.c.c.c:...c.c.c:.c .    :   c   c:cc c c c|
:ccc c c :c c c . :. . c.c.:c.c.c.c.:c.c.c.c.:c.c.c . :. c c c :c c c c |
:cc     c: c      :   ccc.c:.c.c.c.c:.c.c.c.c:.c......:   c   c:cccccc c|
$1B0     $1B1     $1B2     $1B3     $1B4     $1B5     $1B6     $1B7     ;
:c c c c :c c . . :. c.c.c.:c.c.c.c.:c.c.c.c.:c.c c c :. c c c :c c c c |
: c      : c      : . ccc.c:.c.c.c.c:.c.c.c.c:.c.c.. .: . c  #c:cc c c c|
:c c c c :c c . . :c c.c.c :c c.c.c.:c.c.c c :c.c.c . :. c c c :c c c c |
: c      :  .. . .:...c.c..:.. ....c:.c......:...c.. .:     .#c:cccccccc|
:c c c c :c c . c :c c.c.c.:c.c.c.c.:c.c c.c.:c.c.c . :. c c c :ccccc cc|
: c      :     ...:..cc.c.c:.c.c.c.c:.c.c.c.c:.c.c..  :.  .#.#c:cccc c c|
:c c c c :c c . . :. c.c.c.:c.c.c.c.:c.c.c.c.:c.c.c . :c c c c :c c c c |
: c      : .#.   .: ..c.c..:.....c.c:.c.c....: c.c..  :#.#.#. c:cccccc  |
$1C0     $1C1     $1C2     $1C3     $1C4     $1C5     $1C6     $1C7     ;
:c c c c :c c . c :. c.c c :c c c.c.:c.c c c :c c.c . :c c c c :c c c c |
: c      :   . c. : ..c.ccc: .#ccc.c:.c.cc.#c:cc.c....:#    . c:cccc ccc|
:c c c c :c c c.c :c c.c.c.:c c.c.c.:c.c.c.c.:c.c.c.c :. c c c :c c c c |
: c      :   ..c..: ..c.c.c:.c.c.c.c:.c.c.c.c:.c.c.c..:#c c   c: ccc c  |
:c c c c :c c c.c :c c.c.c.:c.c.c.c.:c.c.c.c.:c.c.c.c :. c c c :c c c c |
: c      :    .c.c:cc.c.c.c:.c.c.c.c:.c.c.c.c:.c.c.c..: c c  #c: c c c c|
:c c c c :c c c c.:c c.c.c.:c.c.c.c.:c.c.c.c.:c.c.c.c :c c c c :c c c c |
: c      :     ..c:cccc.c.c:.c.c.c.c:.c.c.c.c:.c.c... : c    # :cc c c c|
$1D0     $1D1     $1D2     $1D3     $1D4     $1D5     $1D6     $1D7     ;
:c c c c :c c c c.:c.c.c.c.:c.c.c.c.:c.c.c.c.:c.c.c . :c c c c :c c c c |
: c      : c c  #.: ccc.c.c:.c.c.c.c:.c...c.c:.c.c..# : c c  # : c c c c|
:c c c c :c c c c :c c.c.c.:c.c.c.c.:c.c c.c.:c.c.c c :c c c c :c c c c |
:cc      :        :# cc.c.c:.c.c.c.c:.c.c.c.c:.c.c..# :      # : ccc    |
:ccc c c :c c c c :. c.c.c.:c.c.c.c.:c.c.c.c.:c.c.c . :c c c c :c c c c |
:cc      :       .:   c.c.c:.c.c.c.c:.c.c.c.c:.c.c    : .   .# : ccccc c|
:c c c c :c c c . :. c c.c.:c.c.c.c.:c.c.c.c.:c.c.c . :. c c c :c c c c |
:cc      :        :    cc.c:.c.c....:.....c.c:.c.. ...:.  .  # : ccc c c|
$1E0     $1E1     $1E2     $1E3     $1E4     $1E5     $1E6     $1E7     ;
:c c c c :c c . . :. . c.c.:c.c.c.c.:c.c.c.c.:c.c . c :c c c c :c c c c |
: c      :   .   .:   #.c.c:.c.c.c.c:.c.c.c.c:.c #  . : . . .#c:cccc c c|
:c c c c :c c . c :.     c :c c c.c.:c.c.c.c.:c .   . :c c c c :c c c c |
:cc      : c ..   :#c c c c: c ..c.c:.c.c.c.c: # #    : .    #c: c c c c|
:ccc c c :c c c c :cccccccc:ccc c.c.:c.c.c.c :. . . c :c c c c :c c c cc|
: c      :  #.# cc: ccccccc:ccc. c.c:.c.. .  : # # c .:.   #.# :   c ccc|
:c c c c :c c c c :c cccccc:ccc c c :c c c c :. . c c :. c c . :c c c c |
: c     #:...c....: ccccccc:ccc  c c: c ccc  : #   # #: # #    :cc ccccc|
$1F0     $1F1     $1F2     $1F3     $1F4     $1F5     $1F6     $1F7     ;
:c c .   :c.c . c :c cccccc:ccc c c :c c c c :. . . . :. . . . :. c c c |
:cc . # c:..#.   #:#ccccccc:ccc. ccc:cccccc #: # # # #: # # # #: # # c  |
:c . . c.:c c c c :c cccccc:ccc c c :c c c c :. . . . :. . . . :. . . c |
: # # #.c:.......#:#ccccccc:ccc. ccc:cccc c #: # # # #: # # # #: # # #  |
:. . . c.:c.c c . :c cccccc:ccc c c :c c c c :. . . . :. . . . :. . . . |
: # # #.c:.c.c...#:#ccccccc:ccc  ccc:cccc c##: # # # #: # # # #: # # #  |
:. . . c.:c.c c.c :. cccccc:ccc c c :c c c c :. . . . :. . . . :. . . . |
: # # #.c:.c......: .#.#.#.:#.#  ccc:cccc  ##: # # # #: # # # #: # # # #|
)"
